---
title: "Overview of Medicaid Income Eligibility Cutoffs Across States and Eligibility Groups"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview of Medicaid Income Eligibility Cutoffs Across States and Eligibility Groups}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(melig)
```

## Income Cutoffs for Pregnant Women and Parents, 2002—2023

```{r Medicaid_Eligibility_Cutoffs_2002-2023, message=FALSE, warning=FALSE, echo=FALSE}
bind_rows(
  melig::parents |> 
  mutate(year = lubridate::ym(paste0(year, month))) |> 
  filter(state == "United States") |> 
  mutate(elig_grp = "Parents"),
  
  melig::pregnant_women |> 
  mutate(year = lubridate::ym(paste0(year, month))) |> 
  filter(state == "United States") |> 
  mutate(elig_grp = "Pregnant Beneficiaries")
) |> 
  mutate(cutoff = cutoff / 100) |> 
  ggplot(aes(x = year, y = cutoff, colour = elig_grp, fill = elig_grp)) +
  geom_point() +
  geom_path() +
  hrbrthemes::theme_ipsum(grid = "XY", plot_title_size = 12) +
  hrbrthemes::scale_y_percent(limits = c(0, 2.5)) +
  theme(legend.position = "top",
        legend.title = element_blank(),
        aspect.ratio = 0.618) +
  labs(x = NULL, y = "Federal Poverl Level",
       title = "Median State-Level Medicaid Income Eligibility Cutoffs, 2002–2023")
```

